services:
  - type: web
    name: musicinsights
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn musicdata.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: musicinsights.onrender.com
